/*
 * This file is part of the VanitySearch distribution (https://github.com/JeanLucPons/VanitySearch).
 * Copyright (c) 2019 Jean Luc PONS.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#include "GPUEngine.h"
#include <cmath>
#include <memory>
#include <fstream>

using namespace std;

void GPUEngine::GenerateCode(Secp256K1 *secp, int size) {
    // Validate input size
    if (size <= 0 || size % 2 != 0) {
        throw runtime_error("Invalid group size. Size must be positive and even.");
    }

    // Use smart pointer for automatic memory management
    unique_ptr<Point[]> Gn(new Point[size]);

    // Compute generator table using more efficient point operations
    Point g = secp->G;
    Gn[0] = g;
    
    // Double the point for the second element
    g = secp->DoubleDirect(g);
    Gn[1] = g;
    
    // Compute remaining points using more efficient addition
    for (int i = 2; i < size; i++) {
        g = secp->AddDirect(g, secp->G);
        Gn[i] = g;
    }

    // Compute _2Gn = CPU_GRP_SIZE*G
    Point _2Gn = secp->DoubleDirect(Gn[size / 2 - 1]);

    // Use modern C++ file operations with RAII
    ofstream f("GPU/GPUGroup.h");
    if (!f.is_open()) {
        throw runtime_error("Failed to open GPU/GPUGroup.h for writing");
    }

    // Write header with improved formatting
    f << "// File generated by GPUEngine::GenerateCode()\n"
      << "// GROUP definitions\n\n"
      << "#pragma once\n"
      << "#define GRP_SIZE " << size << "\n\n"
      << "// _2Gn = GRP_SIZE*G\n"
      << "__device__ __constant__ uint64_t _2Gnx[4] = " << _2Gn.x.GetC64Str(4) << ";\n"
      << "__device__ __constant__ uint64_t _2Gny[4] = " << _2Gn.y.GetC64Str(4) << ";\n\n"
      << "// SecpK1 Generator table (Contains G,2G,3G,...,(GRP_SIZE/2)G)\n"
      << "__device__ __constant__ uint64_t Gx[][4] = {\n";

    // Write x-coordinates
    for (int i = 0; i < size/2; i++) {
        f << "  " << Gn[i].x.GetC64Str(4);
        if (i < size/2 - 1) f << ",";
        f << "\n";
    }
    f << "};\n\n";

    f << "__device__ __constant__ uint64_t Gy[][4] = {\n";
    // Write y-coordinates
    for (int i = 0; i < size/2; i++) {
        f << "  " << Gn[i].y.GetC64Str(4);
        if (i < size/2 - 1) f << ",";
        f << "\n";
    }
    f << "};\n";

    // File is automatically closed when 'f' goes out of scope
}
